### ISSUE TITLE
Incompatible metadata change in version 2.0

### ISSUE THREAD

**Issue by tdiesler** [wildfly-extras/fuse-patch#134]
```
Run command: java -Djboss.home=. -Dlogging.configuration=file:bin/fusepatch-logging.properties -jar jboss-modules.jar -mp modules org.wildfly.extras.patch --update rtgov-distro-server
Error executing command: java.lang.IllegalStateException: Cannot obtain patch id
   at org.wildfly.extras.patch.utils.IllegalStateAssertion.assertTrue(IllegalStateAssertion.java:59) [fuse-patch-core-2.1.0.jar:]
   at org.wildfly.extras.patch.internal.MetadataParser.readPatch(MetadataParser.java:201) [fuse-patch-core-2.1.0.jar:]
   at org.wildfly.extras.patch.internal.MetadataParser.readPatch(MetadataParser.java:88) [fuse-patch-core-2.1.0.jar:]
   at org.wildfly.extras.patch.server.AbstractServer.getPatch(AbstractServer.java:137) [fuse-patch-core-2.1.0.jar:]
   at org.wildfly.extras.patch.internal.DefaultPatchTool.installInternal(DefaultPatchTool.java:119) [fuse-patch-core-2.1.0.jar:]
   at org.wildfly.extras.patch.internal.DefaultPatchTool.update(DefaultPatchTool.java:85) [fuse-patch-core-2.1.0.jar:]
   at org.wildfly.extras.patch.internal.Main.run(Main.java:154) [fuse-patch-core-2.1.0.jar:]
   at org.wildfly.extras.patch.internal.Main.mainInternal(Main.java:74) [fuse-patch-core-2.1.0.jar:]
   at org.wildfly.extras.patch.internal.Main.main(Main.java:55) [fuse-patch-core-2.1.0.jar:]
```

**Comment by tdiesler** [comment]
Is this a real issue (i.e. do we have fuse-patch-1.x rolled out to customers)?

**Comment by djcoleman** [comment]
Yes, Fuse-Patch 1.6.x was used in the GA releases of RT-Gov, S-RAMP and Fuse-EAP 6.2.1.

**Comment by tdiesler** [comment]
ok, I'll get that fixed
