### ISSUE TITLE
wildfly distro does not recognize default repository

### ISSUE THREAD

**Issue by tdiesler** [wildfly-extras/fuse-patch#148]
```
[tdiesler@macbook wildfly-10.0.0.Final]$ java -Djboss.home=. -Dlogging.configuration=file:bin/fusepatch-logging.properties -jar jboss-modules.jar -mp modules org.wildfly.extras.patch --add file:fusepatch/repository/fuse-patch-distro-wildfly-2.3.0-SNAPSHOT.zip 
Error executing command: java.lang.IllegalArgumentException: Null repository
	at org.wildfly.extras.patch.utils.IllegalArgumentAssertion.assertNotNull(IllegalArgumentAssertion.java:39) [fuse-patch-core-2.3.0-SNAPSHOT.jar:]
	at org.wildfly.extras.patch.internal.DefaultPatchTool.<init>(DefaultPatchTool.java:43) [fuse-patch-core-2.3.0-SNAPSHOT.jar:]
	at org.wildfly.extras.patch.PatchToolBuilder.build(PatchToolBuilder.java:101) [fuse-patch-core-2.3.0-SNAPSHOT.jar:]
	at org.wildfly.extras.patch.internal.Main.run(Main.java:133) [fuse-patch-core-2.3.0-SNAPSHOT.jar:]
	at org.wildfly.extras.patch.internal.Main.mainInternal(Main.java:74) [fuse-patch-core-2.3.0-SNAPSHOT.jar:]
	at org.wildfly.extras.patch.internal.Main.main(Main.java:55) [fuse-patch-core-2.3.0-SNAPSHOT.jar:]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) [rt.jar:1.8.0_92]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) [rt.jar:1.8.0_92]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) [rt.jar:1.8.0_92]
	at java.lang.reflect.Method.invoke(Method.java:498) [rt.jar:1.8.0_92]
	at org.jboss.modules.Module.run(Module.java:329) [jboss-modules.jar:1.5.1.Final]
	at org.jboss.modules.Main.main(Main.java:507) [jboss-modules.jar:1.5.1.Final]
```

**Comment by tdiesler** [comment]
The default repository URL is currently derived from the CodeSource path of Main class. If fuse-patch is installed via feature-pack, this would be somewhere in the local maven repo, which is unrelated to the server home
